/*

 BLACKCLEARMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 1 x 1
   Tile set      : Z:\home\yoshi100\Bureau\dev\C\gameboyprog\outils-tuto\gb tile develop\BlackClear.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define BlackClearMapWidth 1
#define BlackClearMapHeight 1
#define BlackClearMapBank 0

extern unsigned char BlackClearMap[];

/* End of BLACKCLEARMAP.H */
