/*

 HOME.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : Z:\home\yoshi100\Bureau\dev\C\gameboyprog\outils-tuto\gb tile develop\home.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define HomeWidth 20
#define HomeHeight 18
#define HomeBank 0

extern unsigned char Home[];

/* End of HOME.H */
