/*

 HOMECHEST.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 1 x 2
   Tile set      : Z:\home\yoshi100\Bureau\dev\C\gameboyprog\outils-tuto\gb tile develop\home.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define HomeChestWidth 1
#define HomeChestHeight 2
#define HomeChestBank 0

extern unsigned char HomeChest[];

/* End of HOMECHEST.H */
