/*

 MAPTOWNMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 22 x 19
   Tile set      : Z:\home\yoshi100\Bureau\dev\C\gameboyprog\outils-tuto\gb tile develop\MapTown.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define MapTownMapWidth 22
#define MapTownMapHeight 19
#define MapTownMapBank 0

extern unsigned char MapTownMap[];

/* End of MAPTOWNMAP.H */
