/*

 TEXTNES.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 5
   Tile set      : Z:\home\yoshi100\Bureau\dev\C\gameboyprog\outils-tuto\gb tile develop\alphabet.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define textNESWidth 20
#define textNESHeight 5
#define textNESBank 0

extern unsigned char textNES[];

/* End of TEXTNES.H */
