/*

 TITLESCREENMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : Z:\home\yoshi100\Bureau\dev\C\gameboyprog\outils-tuto\gb tile develop\TitleScreen.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define TitleScreenMapWidth 20
#define TitleScreenMapHeight 18
#define TitleScreenMapBank 0

extern unsigned char TitleScreenMap[];

/* End of TITLESCREENMAP.H */
